name: Deploy to EC2

on:
  push:
    branches:
      - main # You can specify the branch to trigger deployments

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY_SSH }} # This should be the name of your private SSH key secret

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /path/to/your/project
            git pull origin main
            npm install
            pm2 restart next-app
          EOF
